import {
  EventCategory,
  EventStatus,
  OrderStatus,
  OrganizerStatus,
  ScanResultStatus,
  TicketStatus,
  TicketTypeStatus,
  UserRole,
} from '../../data-access/models';

export const appLabels = {
  brand: {
    name: 'Bolexa',
    scannerName: 'Bolexa Scan',
    homeAriaLabel: 'Bolexa home',
  },
  navigation: {
    primaryAriaLabel: 'Principal',
    organizerAriaLabel: 'Organizador',
    organizerMobileAriaLabel: 'Organizador movil',
    scannerAriaLabel: 'Scanner',
    publicLinks: {
      events: 'Eventos',
      myTickets: 'Mis tickets',
      organizer: 'Organizador',
      scanner: 'Scanner',
    },
    organizerLinks: {
      dashboard: 'Dashboard',
      events: 'Eventos',
      orders: 'Ordenes',
      attendees: 'Asistentes',
      reports: 'Reportes',
    },
    scannerLinks: {
      events: 'Eventos',
      scanner: 'Scanner',
      attendees: 'Asistentes',
      stats: 'Stats',
    },
    actions: {
      sellEvent: 'Vende tu evento',
      viewMarketplace: 'Ver marketplace',
    },
  },
  auth: {
    switcherPrefix: 'Entrar como',
    roleLabels: {
      consumer: 'Comprador',
      organizer: 'Organizador',
      scanner: 'Scanner',
      admin: 'Admin',
    } satisfies Record<UserRole, string>,
  },
  shells: {
    organizer: {
      subtitle: 'Portal organizador',
      demoContext: 'Producciones Avila · Demo',
    },
    scanner: {
      mode: 'Modo operativo',
    },
  },
  home: {
    badge: 'MVP demo · Dark mode first',
    headline: 'La boleteria moderna de Venezuela.',
    description: 'Descubre eventos, compra facil y entra rapido con tickets QR. Bolexa conecta compradores, organizadores y equipos de acceso en una sola plataforma.',
    primaryCta: 'Explorar eventos',
    secondaryCta: 'Ver demo organizador',
    stats: [
      {
        value: '3',
        description: 'Superficies: comprador, organizador y scanner.',
        tone: 'primary',
      },
      {
        value: 'QR',
        description: 'Tickets validables para entrada rapida.',
        tone: 'success',
      },
      {
        value: 'VE',
        description: 'Pago movil, Zelle, USDT y pagos manuales.',
        tone: 'warning',
      },
    ],
    featured: {
      eyebrow: 'Evento destacado',
      title: 'Evento destacado',
    },
    categories: {
      eyebrow: 'Categorias',
      title: 'Encuentra el plan que quieres vivir',
      description: 'Conciertos, running, teatro, tecnologia, deportes y experiencias nocturnas en una sola plataforma.',
      pills: [
        'Conciertos',
        'Running',
        'Teatro',
        'Conferencias',
        'Fiestas',
        'Deportes',
      ],
    },
    upcoming: {
      eyebrow: 'Proximamente',
      title: 'Eventos destacados',
      description: 'Una seleccion inicial de eventos venezolanos para probar el flujo completo del MVP.',
      emptyTitle: 'No hay eventos publicados',
      emptyDescription: 'Cuando existan eventos publicados, apareceran en esta seccion.',
    },
    organizerCta: {
      eyebrow: 'Para organizadores',
      title: 'Vende tu evento con Bolexa',
      description: 'Publica eventos, configura tickets, controla ventas y valida accesos desde una experiencia moderna.',
      primaryCta: 'Abrir dashboard demo',
      secondaryCta: 'Crear evento',
    },
    footer: 'Bolexa MVP · Plataforma de ticketing para eventos en vivo en Venezuela.',
    capabilityCards: [
      {
        eyebrow: 'Scanner',
        title: 'Ticket valido',
        tone: 'success',
      },
      {
        eyebrow: 'Ordenes',
        title: 'Pago manual',
        tone: 'warning',
      },
      {
        eyebrow: 'Dashboard',
        title: 'Ventas en vivo',
        tone: 'primary',
      },
    ],
  },
  eventsList: {
    eyebrow: 'Marketplace',
    title: 'Eventos en Venezuela',
    description: 'Busca conciertos, carreras, conferencias, teatro, deportes y fiestas con tickets QR.',
    searchPlaceholder: 'Buscar por evento o descripcion',
    filters: {
      category: 'Categoria',
      city: 'Ciudad',
      date: 'Fecha',
      allCategories: 'Todas las categorias',
      allCities: 'Todas las ciudades',
      allDates: 'Todas las fechas',
      next90Days: 'Proximos 90 dias',
      later: 'Mas adelante',
    },
    results: {
      singular: 'evento encontrado',
      plural: 'eventos encontrados',
    },
    empty: {
      title: 'No encontramos eventos',
      description: 'Prueba cambiando la busqueda, ciudad, categoria o fecha.',
    },
  },
  eventDetail: {
    backToEvents: 'Volver a eventos',
    category: 'Categoria',
    date: 'Fecha y hora',
    venue: 'Lugar',
    organizer: 'Organizador',
    description: 'Sobre el evento',
    tickets: 'Selecciona tus tickets',
    trustTitle: 'Compra segura con Bolexa',
    trustItems: [
      'Ticket QR unico por asistente.',
      'Confirmacion simulada por Pago movil, Zelle, USDT o pago manual.',
      'Entrada rapida con validacion por scanner.',
    ],
    summaryTitle: 'Tu seleccion',
    noTicketsSelected: 'Selecciona al menos un ticket para continuar.',
    continueToCheckout: 'Continuar al checkout',
    unavailable: 'No hay tickets disponibles para este evento.',
    notFoundTitle: 'Evento no encontrado',
    notFoundDescription: 'El evento que buscas no existe o no esta publicado.',
    loadingTitle: 'Cargando evento',
  },
  checkout: {
    backToEvent: 'Volver al evento',
    eyebrow: 'Checkout',
    title: 'Completa tu compra',
    description: 'Simula el pago y genera tickets QR desde el mock store de Bolexa.',
    eventSummary: 'Resumen del evento',
    buyerInfo: 'Datos del comprador',
    tickets: 'Tickets',
    payment: 'Metodo de pago',
    paymentInstructions: 'Instrucciones de pago',
    fields: {
      name: 'Nombre completo',
      email: 'Correo electronico',
      phone: 'Telefono',
      reference: 'Referencia de pago',
    },
    placeholders: {
      name: 'Andrea Perez',
      email: 'andrea@example.com',
      phone: '+58 414-000-0000',
      reference: 'Ej. PM-123456, Zelle ID o hash USDT',
    },
    paymentMethods: {
      pago_movil: 'Pago movil',
      zelle: 'Zelle',
      binance: 'Binance/USDT',
      bank_transfer: 'Transferencia bancaria',
      manual: 'Pago manual',
      card: 'Tarjeta (placeholder)',
    },
    methodDescriptions: {
      pago_movil: 'Usa un pago movil demo y coloca una referencia simulada.',
      zelle: 'Simula una transferencia Zelle con correo o referencia.',
      binance: 'Simula un pago USDT/Binance con hash o ID de transaccion.',
      bank_transfer: 'Simula una transferencia bancaria nacional.',
      manual: 'Envia la orden a revision manual para confirmar luego.',
      card: 'Metodo reservado para una integracion futura de tarjeta.',
    },
    approvedCta: 'Simular pago aprobado',
    manualReviewCta: 'Enviar a revision manual',
    processing: 'Procesando orden...',
    noTicketsSelected: 'Selecciona al menos un ticket para continuar.',
    unavailable: 'No hay tickets disponibles para este evento.',
    notFoundTitle: 'Checkout no disponible',
    notFoundDescription: 'No encontramos el evento para esta compra.',
    errorTitle: 'No pudimos procesar la orden',
    loadingTitle: 'Cargando checkout',
  },
  routePlaceholder: {
    defaults: {
      eyebrow: 'Bolexa MVP',
      title: 'Pantalla en progreso',
      description: 'Esta ruta ya esta conectada y lista para recibir UI final.',
      primaryLink: '/',
      primaryLabel: 'Volver al inicio',
    },
  },
  notFound: {
    code: '404',
    title: 'Ruta no encontrada',
    description: 'Esta pantalla no existe en el MVP de Bolexa.',
    cta: 'Volver al inicio',
  },
  shared: {
    statusBadge: {
      fallback: 'Estado',
      event: {
        draft: 'Borrador',
        published: 'Publicado',
        cancelled: 'Cancelado',
        completed: 'Completado',
      } satisfies Record<EventStatus, string>,
      organizer: {
        pending: 'Pendiente',
        active: 'Activo',
        suspended: 'Suspendido',
      } satisfies Record<OrganizerStatus, string>,
      ticketType: {
        active: 'Activo',
        paused: 'Pausado',
        sold_out: 'Agotado',
      } satisfies Record<TicketTypeStatus, string>,
      order: {
        pending: 'Pendiente',
        paid: 'Pagado',
        cancelled: 'Cancelado',
        expired: 'Expirado',
        refunded: 'Reembolsado',
        manual_review: 'Revision manual',
        failed: 'Fallido',
      } satisfies Record<OrderStatus, string>,
      ticket: {
        valid: 'Valido',
        used: 'Usado',
        cancelled: 'Cancelado',
        refunded: 'Reembolsado',
      } satisfies Record<TicketStatus, string>,
      scan: {
        accepted: 'Valido',
        already_used: 'Ya usado',
        invalid_ticket: 'Invalido',
        wrong_event: 'Evento incorrecto',
        cancelled: 'Cancelado',
        refunded: 'Reembolsado',
      } satisfies Record<ScanResultStatus, string>,
    },
    emptyState: {
      eyebrow: 'Sin resultados',
      title: 'No hay informacion para mostrar',
      description: 'Cuando existan datos disponibles, apareceran aqui.',
      actionLabel: 'Volver al inicio',
    },
    loadingState: {
      title: 'Cargando informacion',
    },
    searchInput: {
      label: 'Buscar',
      placeholder: 'Buscar eventos, asistentes u ordenes',
      clear: 'Limpiar',
    },
    eventCard: {
      noImage: 'Imagen del evento',
      from: 'Desde',
      available: 'disponibles',
      soldOut: 'Agotado',
      viewEvent: 'Ver evento',
      categories: {
        concert: 'Concierto',
        sports: 'Deportes',
        running: 'Running',
        theater: 'Teatro',
        conference: 'Conferencia',
        party: 'Fiesta',
        festival: 'Festival',
        other: 'Otro',
      } satisfies Record<EventCategory, string>,
    },
    ticketTypeSelector: {
      each: 'c/u',
      available: 'disponibles',
      quantity: 'Cantidad',
      decrement: 'Restar ticket',
      increment: 'Sumar ticket',
      unavailable: 'No disponible',
    },
    orderSummary: {
      title: 'Resumen de orden',
      empty: 'No hay tickets seleccionados.',
      subtotal: 'Subtotal',
      fees: 'Comision Bolexa',
      total: 'Total',
    },
    qrTicketCard: {
      official: 'Ticket oficial',
      holder: 'Titular',
      ticketType: 'Tipo de ticket',
      qrCode: 'Codigo QR',
      instructions: 'Presenta este codigo en la entrada. Cada ticket solo puede validarse una vez.',
    },
    scanResultPanel: {
      idleTitle: 'Esperando ticket',
      idleMessage: 'Escanea o ingresa un codigo QR para validar la entrada.',
      holder: 'Titular',
      ticketType: 'Tipo de ticket',
      checkedInAt: 'Check-in',
      defaultMessages: {
        accepted: 'Ticket valido para este evento.',
        already_used: 'Este ticket ya fue utilizado.',
        invalid_ticket: 'No encontramos un ticket con ese codigo QR.',
        wrong_event: 'Este ticket pertenece a otro evento.',
        cancelled: 'Este ticket fue cancelado.',
        refunded: 'Este ticket fue reembolsado.',
      } satisfies Record<ScanResultStatus, string>,
    },
  },
  routes: {
    eventsList: {
      eyebrow: 'Marketplace',
      title: 'Eventos en Venezuela',
      description: 'Listado publico con busqueda, filtros por ciudad, categoria y fecha.',
    },
    eventDetail: {
      eyebrow: 'Detalle de evento',
      title: 'Evento, tickets y CTA de compra',
      description: 'Pantalla preparada para cargar evento por slug y seleccionar tipos de ticket.',
      primaryLink: '/checkout/event-caracas-music-fest',
      primaryLabel: 'Ir al checkout demo',
    },
    checkout: {
      eyebrow: 'Checkout',
      title: 'Pago venezolano simulado',
      description: 'Flujo listo para Pago movil, Zelle, Binance/USDT, transferencia y pago manual.',
      primaryLink: '/checkout/event-caracas-music-fest/confirmation/order-1001',
      primaryLabel: 'Ver confirmacion demo',
    },
    confirmation: {
      eyebrow: 'Confirmacion',
      title: 'Orden confirmada',
      description: 'Estado de compra, resumen de tickets y enlace a Mis tickets.',
      primaryLink: '/my-tickets',
      primaryLabel: 'Ver mis tickets',
    },
    myTickets: {
      eyebrow: 'Mis tickets',
      title: 'Tickets del comprador demo',
      description: 'Listado de tickets validos, usados y futuros del usuario mock.',
      primaryLink: '/my-tickets/ticket-1001',
      primaryLabel: 'Abrir ticket QR demo',
    },
    ticketDetail: {
      eyebrow: 'Ticket QR',
      title: 'Ticket oficial Bolexa',
      description: 'Detalle con QR, titular, tipo de ticket, estado e instrucciones de entrada.',
    },
    profile: {
      eyebrow: 'Perfil',
      title: 'Perfil del usuario demo',
      description: 'Datos basicos y preferencias del comprador.',
    },
    organizerDashboard: {
      eyebrow: 'Organizador',
      title: 'Dashboard de ventas',
      description: 'Metricas de revenue, tickets vendidos, check-ins, eventos proximos y ordenes recientes.',
      primaryLink: '/organizer/events',
      primaryLabel: 'Ver eventos',
    },
    organizerEvents: {
      eyebrow: 'Organizador',
      title: 'Gestion de eventos',
      description: 'Tabla de eventos con estados, ventas, acciones y acceso a configuracion.',
      primaryLink: '/organizer/events/new',
      primaryLabel: 'Crear evento demo',
    },
    organizerNewEvent: {
      eyebrow: 'Organizador',
      title: 'Crear evento',
      description: 'Formulario mock para datos basicos, venue, fecha, categoria, cover y estado.',
    },
    organizerEventDetail: {
      eyebrow: 'Organizador',
      title: 'Detalle operativo del evento',
      description: 'Resumen del evento y accesos a tickets, ordenes, asistentes y reportes.',
    },
    organizerEditEvent: {
      eyebrow: 'Organizador',
      title: 'Editar evento',
      description: 'Formulario de edicion conectado al mock store.',
    },
    organizerTicketTypes: {
      eyebrow: 'Organizador',
      title: 'Tipos de ticket',
      description: 'Inventario, precios, cantidades y estados de venta.',
    },
    organizerOrders: {
      eyebrow: 'Organizador',
      title: 'Ordenes del evento',
      description: 'Ordenes por comprador, estado, total, metodo de pago y fecha.',
    },
    organizerAttendees: {
      eyebrow: 'Organizador',
      title: 'Asistentes',
      description: 'Listado de asistentes, tipo de ticket, estado de check-in y export CSV.',
    },
    organizerReports: {
      eyebrow: 'Organizador',
      title: 'Reportes',
      description: 'Revenue, tickets vendidos, pagos y progreso de entrada por evento.',
    },
    scannerEvents: {
      eyebrow: 'Scanner',
      title: 'Seleccion de evento',
      description: 'Lista de eventos asignados con progreso de entrada.',
      primaryLink: '/scan/events/event-caracas-music-fest/scanner',
      primaryLabel: 'Abrir scanner demo',
    },
    scannerEventSummary: {
      eyebrow: 'Scanner',
      title: 'Resumen de evento',
      description: 'Contexto operativo antes de empezar a validar tickets.',
    },
    scannerPage: {
      eyebrow: 'Scanner',
      title: 'Validacion QR',
      description: 'Camara placeholder, input manual de QR y estados valido/usado/invalido.',
    },
    scannerAttendees: {
      eyebrow: 'Scanner',
      title: 'Busqueda manual',
      description: 'Fallback por nombre o email cuando no se puede escanear el QR.',
    },
    scannerStats: {
      eyebrow: 'Scanner',
      title: 'Stats de entrada',
      description: 'Total de tickets, ingresados, pendientes y ultimos check-ins.',
    },
  },
} as const;
